### ISSUE TITLE
默认不启用新功能

### ISSUE THREAD

**Issue by TCOTC** [hqweay/siyuan-hqweay-go#1]
边栏突然出现了几个没用的图标：

![b739f838d2dac2ba0f959bce9968417d](https://github.com/hqweay/siyuan-hqweay-go/assets/78434827/a3c4cd07-73de-4fd3-b222-f2f23ffe6f99)

排查之后发现是更新插件之后默认启用了不需要的功能：

![image](https://github.com/hqweay/siyuan-hqweay-go/assets/78434827/b8c6a33b-b4e8-4e52-bd2b-7d2305eb4502)

**Comment by hqweay** [comment]
造成困扰了，感谢提醒，下次更新改成默认不启用

**Comment by hqweay** [comment]
更新了版
