### ISSUE TITLE
随机题头图能有用吗？感觉不生效啊

### ISSUE THREAD

**Issue by xiaofeng010766** [hqweay/siyuan-hqweay-go#6]
![image](https://github.com/user-attachments/assets/c524d4da-ff5a-4145-a283-4c64395d0e8a)
![image](https://github.com/user-attachments/assets/726489ed-ec49-4d16-98ba-045f17263c93)

都设置了，也重启了，但是发现没啥用

**Comment by hqweay** [comment]
![CleanShot 2024-12-04 at 19 36 04@2x](https://github.com/user-attachments/assets/6001c1d1-ecca-4194-8ab9-4b79b9a1a244)

右键点击这里无效吗？

**Comment by xiaofeng010766** [comment]
> ![CleanShot 2024-12-04 at 19 36 04@2x](https://private-user-images.githubusercontent.com/23608642/392358889-6001c1d1-ecca-4194-8ab9-4b79b9a1a244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzM5MDUsIm5iZiI6MTczMzczMzYwNSwicGF0aCI6Ii8yMzYwODY0Mi8zOTIzNTg4ODktNjAwMWMxZDEtZWNjYS00MTk0LThhYjktNGI3OWI5YTFhMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWUwY2NiMDdmNTI1YjJlNzliMTZmNGRiZmVkNjJhMzlmMTliNDg3MTYwZDU3YzA4NTIzNjhkMjIzZWEyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgSvVQRyM7BANbLAeG2Mld-_TwaUByxjqS62WdnUJpc)
> 
> 右键点击这里无效吗？

不行，感觉没生效就是使用的思源自带的题头图

https://github.com/user-attachments/assets/2e3973a9-e1d4-4e3f-84cb-dd16dc619c2b

**Comment by hqweay** [comment]
> > ![CleanShot 2024-12-04 at 19 36 04@2x](https://private-user-images.githubusercontent.com/23608642/392358889-6001c1d1-ecca-4194-8ab9-4b79b9a1a244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzM5MDUsIm5iZiI6MTczMzczMzYwNSwicGF0aCI6Ii8yMzYwODY0Mi8zOTIzNTg4ODktNjAwMWMxZDEtZWNjYS00MTk0LThhYjktNGI3OWI5YTFhMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWUwY2NiMDdmNTI1YjJlNzliMTZmNGRiZmVkNjJhMzlmMTliNDg3MTYwZDU3YzA4NTIzNjhkMjIzZWEyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgSvVQRyM7BANbLAeG2Mld-_TwaUByxjqS62WdnUJpc)
> > 右键点击这里无效吗？
> 
> 不行，感觉没生效就是使用的思源自带的题头图
> 
>  Longshot20241209164609.mov

你使用的鼠标吗？鼠标 右键 点击试试呢~我看你是左键点击了。

**Comment by xiaofeng010766** [comment]
> > > ![CleanShot 2024-12-04 at 19 36 04@2x](https://private-user-images.githubusercontent.com/23608642/392358889-6001c1d1-ecca-4194-8ab9-4b79b9a1a244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzM5MDUsIm5iZiI6MTczMzczMzYwNSwicGF0aCI6Ii8yMzYwODY0Mi8zOTIzNTg4ODktNjAwMWMxZDEtZWNjYS00MTk0LThhYjktNGI3OWI5YTFhMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWUwY2NiMDdmNTI1YjJlNzliMTZmNGRiZmVkNjJhMzlmMTliNDg3MTYwZDU3YzA4NTIzNjhkMjIzZWEyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgSvVQRyM7BANbLAeG2Mld-_TwaUByxjqS62WdnUJpc)
> > > 右键点击这里无效吗？
> > 
> > 
> > 不行，感觉没生效就是使用的思源自带的题头图
> > Longshot20241209164609.mov
> 
> 你使用的鼠标吗？鼠标 右键 点击试试呢~我看你是左键点击了。

右键好像可以，但是感觉切换比较慢，就是我右键点击后可能要好几秒才会变换图片

**Comment by hqweay** [comment]
> > > > ![CleanShot 2024-12-04 at 19 36 04@2x](https://private-user-images.githubusercontent.com/23608642/392358889-6001c1d1-ecca-4194-8ab9-4b79b9a1a244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzM5MDUsIm5iZiI6MTczMzczMzYwNSwicGF0aCI6Ii8yMzYwODY0Mi8zOTIzNTg4ODktNjAwMWMxZDEtZWNjYS00MTk0LThhYjktNGI3OWI5YTFhMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWUwY2NiMDdmNTI1YjJlNzliMTZmNGRiZmVkNjJhMzlmMTliNDg3MTYwZDU3YzA4NTIzNjhkMjIzZWEyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgSvVQRyM7BANbLAeG2Mld-_TwaUByxjqS62WdnUJpc)
> > > > 右键点击这里无效吗？
> > > 
> > > 
> > > 不行，感觉没生效就是使用的思源自带的题头图
> > > Longshot20241209164609.mov
> > 
> > 
> > 你使用的鼠标吗？鼠标 右键 点击试试呢~我看你是左键点击了。
> 
> 右键好像可以，但是感觉切换比较慢，就是我右键点击后可能要好几秒才会变换图片，还有就是使用了这个题头图会保存在本地吗？ 比如第一张是A图，然后我右击再次点击切换，切换成B图，那么A、B这2张图会保存在我本地吗？如果在后期是否需要进行清理


比较慢是因为默认配置的通过接口获取图片链接，有网络延迟。
因为使用的图片链接，不会保存到本地，不需要清理。

**Comment by xiaofeng010766** [comment]
> > > > > ![CleanShot 2024-12-04 at 19 36 04@2x](https://private-user-images.githubusercontent.com/23608642/392358889-6001c1d1-ecca-4194-8ab9-4b79b9a1a244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzM5MDUsIm5iZiI6MTczMzczMzYwNSwicGF0aCI6Ii8yMzYwODY0Mi8zOTIzNTg4ODktNjAwMWMxZDEtZWNjYS00MTk0LThhYjktNGI3OWI5YTFhMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWUwY2NiMDdmNTI1YjJlNzliMTZmNGRiZmVkNjJhMzlmMTliNDg3MTYwZDU3YzA4NTIzNjhkMjIzZWEyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgSvVQRyM7BANbLAeG2Mld-_TwaUByxjqS62WdnUJpc)
> > > > > 右键点击这里无效吗？
> > > > 
> > > > 
> > > > 不行，感觉没生效就是使用的思源自带的题头图
> > > > Longshot20241209164609.mov
> > > 
> > > 
> > > 你使用的鼠标吗？鼠标 右键 点击试试呢~我看你是左键点击了。
> > 
> > 
> > 右键好像可以，但是感觉切换比较慢，就是我右键点击后可能要好几秒才会变换图片，还有就是使用了这个题头图会保存在本地吗？ 比如第一张是A图，然后我右击再次点击切换，切换成B图，那么A、B这2张图会保存在我本地吗？如果在后期是否需要进行清理
> 
> 比较慢是因为默认配置的通过接口获取图片链接，有网络延迟。 因为使用的图片链接，不会保存到本地，不需要清理。

好的，非常感谢，但是我貌似发现了个bug,提了个新的issue
